# yaml-language-server: $schema=./node_modules/harperdb/config-app.schema.json

# This is the configuration file for the application.
# It specifies built-in Harper components that will load the specified feature and files.
# For more information, see https://docs.harperdb.io/docs/reference/components/built-in-extensions

# Follow along with https://github.com/HarperFast/create-your-first-application to learn more!
